import Rodape from "./componentes/Rodape";
import SecaoBanner from "./componentes/SecaoBanner";
import SecaoExperienciaTrabalho from "./componentes/SecaoExperienciaTrabalho";
import Topo from "./componentes/Topo";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Topo />
        <SecaoBanner />
        <SecaoExperienciaTrabalho />
        <Rodape />
        {children}
      </body>
    </html>
  );
}
